[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solspin = "6jNcqtLkYWrPKTY8sSmKJKitYUapmk1RGz22vzv55t7n"

[programs.devnet]
solspin = "6jNcqtLkYWrPKTY8sSmKJKitYUapmk1RGz22vzv55t7n"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"  # Changed from "localnet" to "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""